name: CI - Linting & Type Checking

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to test'
        required: false
        default: 'main'
  workflow_call:
    inputs:
      ref:
        description: 'Git ref to test'
        required: false
        type: string
        default: 'main'

jobs:
  ci-checks:
    name: "🔍 CI: Lint & Type Check"
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref || github.ref }}
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies (single attempt)
      run: npm ci --prefer-offline --no-audit 2>/dev/null || npm install --prefer-offline --no-audit
      
    - name: Run ESLint
      run: |
        echo "📝 Running ESLint..."
        npm run lint
        echo "✅ Linting completed successfully!"
      
    - name: Run TypeScript type check
      run: |
        echo "🔍 Running TypeScript type check..."
        npx tsc --noEmit
        echo "✅ Type checking completed successfully!"
        
    - name: CI Summary
      run: |
        echo "✅ All CI checks passed!"
        echo "🎉 Code quality validation completed successfully!"