name: Test-3 Build

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to test'
        required: false
        default: 'main'
  workflow_call:
    inputs:
      ref:
        description: 'Git ref to test'
        required: false
        type: string
        default: 'main'

jobs:
  build:
    name: "🏗️ Build Application"
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref || github.ref }}
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies with retry
      run: |
        for i in {1..3}; do
          echo "Attempt $i to install dependencies..."
          # First try npm ci, if it fails due to lock file mismatch, use npm install
          if npm ci --prefer-offline --no-audit 2>/dev/null; then
            echo "Dependencies installed successfully with npm ci!"
            break
          elif npm install --prefer-offline --no-audit; then
            echo "Dependencies installed successfully with npm install!"
            break
          else
            echo "Attempt $i failed, retrying in 10 seconds..."
            sleep 10
          fi
          if [ $i -eq 3 ]; then
            echo "All attempts failed"
            exit 1
          fi
        done
      
    - name: Build Next.js application
      run: npm run build
      
    - name: Verify build artifacts
      run: |
        if [ ! -d ".next" ]; then
          echo "❌ Build failed - .next directory not found"
          exit 1
        fi
        echo "✅ Build successful - artifacts created!"
        ls -la .next/
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test3-build-${{ github.run_id }}-${{ github.run_attempt }}
        path: |
          .next/
          public/
        retention-days: 1
        
    - name: Test Result Summary
      run: |
        echo "✅ Test-3 (Build) - PASSED"
        echo "RESULT=PASSED" >> $GITHUB_OUTPUT
      id: result
